### ISSUE TITLE
Round time before computing timedelta

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom-preproc#3]
Coming from https://github.com/metno/pyaerocom/issues/862#issuecomment-1557059984

In `check_obs.py` (at least  line 145), we should round the time (perhaps to the nearest minute), to avoid rounding errors in dealing with nanoseconds.

**Comment by avaldebe** [comment]
@lewisblake where can I find the NetCDF file from the original comment?
I would like to use its time coordinate to write a test...

**Comment by lewisblake** [comment]
Forwarded you an email

**Comment by avaldebe** [comment]
I can fix the error by rounding to minutes, as you sugested

```
$ pya-pp  report-obs icos-co2 data/202304/01/icos-co2-nrt-bir-10.0m-20230401-20230403T100446.nc --clear-cache
icos-co2-nrt-bir-10.0m-20230401-20230403T100446.nc - time_checker - not a full year
icos-co2-nrt-bir-10.0m-20230401-20230403T100446.nc - data_checker - missing obs found
```

Can we add this file to the repository as a test file?

**Comment by lewisblake** [comment]
Great! Yes, this is publicly available data, so I think it would be fine to include as a test file
